### ISSUE TITLE
issue with generating destination css file

### ISSUE THREAD

**Issue by thefill** [pure-css/grunt-pure-grids#4]
Every time I run pure_grid task I receive: "Running "pure_grids:dest" (pure_grids) task" & one file in root dir with name: 'dest'

Seems like target destination path is lost somewhere.

Fixed it temporary by modifying pure_grids.js:

```
grunt.registerMultiTask('pure_grids', 'Generate custom units for Pure Grids', function() {
    var options = this.options({
        indent: '    '
    });
    var dest = this.data;
    var units = options.units;
    delete options.units;

    // Iterate over all specified file groups.
    this.files.forEach(function(fileGroup) {
        var css = rework('').use(pureGrids.units(units, options));

        grunt.file.write(dest, css.toString(options));
        grunt.log.writeln('File "' + dest + '" created.');
    });
});
```

Hope that will help you to fix it ;-)

**Comment by EkAndreas** [comment]
Still getting the "dest" if I follow the bower install guide.

**Comment by DustinJSilk** [comment]
So weird, because it has always worked before, not sure whats happening now, but this is a new mac im running it on.. Same OS though. Oh well, glad I didnt have to dig into the plugin myself thanks!
